"use client";
import {FormEvent,useState} from "react";
import {CheckCircle2,Clock3,Mail,MapPin,MessageCircle,Phone,Send} from "lucide-react";
import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";
import {sendContactMessage} from "../../lib/supabase";

export default function ContactPage(){
 const [form,setForm]=useState({name:"",email:"",phone:"",subject:"Demande d’information",message:""});
 const [busy,setBusy]=useState(false);const [sent,setSent]=useState(false);const [error,setError]=useState("");
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await sendContactMessage(form);setSent(true);setForm({name:"",email:"",phone:"",subject:"Demande d’information",message:""})}catch(err){setError(err instanceof Error?err.message:"Envoi impossible")}finally{setBusy(false)}};
 return <><SiteHeader/><main className="contact-page"><section className="contact-hero"><small>CONTACT DIRECT • BAMAKO</small><h1>Parlons de votre <em>projet.</em></h1><p>Produit, installation, énergie ou maison connectée : décrivez votre besoin. Notre équipe vous répond avec une solution claire et adaptée.</p></section><section className="contact-layout"><div className="contact-details"><span>ÉQUIPE LOCALE</span><h2>Un expert Fantomas Tech à votre écoute.</h2><p>Vous pouvez nous écrire depuis ce formulaire ou nous joindre immédiatement par téléphone et WhatsApp.</p><div><MapPin/><span><b>Showroom</b><small>Niamana, à côté de la Mairie — Bamako, Mali</small></span></div><div><Phone/><span><b>Téléphone</b><a href="tel:+22371000048">+223 71 00 00 48</a></span></div><div><Mail/><span><b>E-mail</b><a href="mailto:contact@fantomas.tech">contact@fantomas.tech</a></span></div><div><Clock3/><span><b>Horaires</b><small>Lundi–samedi, 8h30–18h30</small></span></div><a className="contact-whatsapp" href="https://wa.me/22371000048?text=Bonjour%20Fantomas%20Tech%2C%20je%20souhaite%20vous%20contacter."><MessageCircle/>Discuter sur WhatsApp</a></div><div className="contact-form-card">{sent?<div className="contact-sent"><CheckCircle2/><h2>Message envoyé.</h2><p>Votre demande est maintenant visible dans l’espace administrateur. Notre équipe vous répondra rapidement.</p><button onClick={()=>setSent(false)}>Envoyer un autre message</button></div>:<form onSubmit={submit}><div><small>FORMULAIRE SÉCURISÉ</small><h2>Envoyez-nous un message</h2></div><label>Nom complet<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Votre nom"/></label><div className="contact-two"><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="vous@email.com"/></label><label>Téléphone / WhatsApp<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+223 …"/></label></div><label>Objet<select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}><option>Demande d’information</option><option>Conseil produit</option><option>Demande de devis</option><option>Installation et maintenance</option><option>Service après-vente</option><option>Autre demande</option></select></label><label>Votre message<textarea required minLength={5} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Expliquez-nous votre besoin…"/></label>{error&&<p className="contact-error">{error}</p>}<button disabled={busy}><Send/>{busy?"Envoi en cours…":"Envoyer le message"}</button><small className="contact-note">En envoyant ce formulaire, vous acceptez d’être recontacté au sujet de votre demande.</small></form>}</div></section></main><SiteFooter/></>;
}
