"use client";

import {useParams} from "next/navigation";
import {ArrowLeft,CheckCircle2,MessageCircle,ShoppingBag,ShieldCheck,Truck,Zap} from "lucide-react";
import SiteHeader from "../../components/SiteHeader";
import SiteFooter from "../../components/SiteFooter";
import {money,products} from "../page";

const root="https://www.fantomas.tech";

const categoryCopy:Record<string,{description:string;uses:string[];features:string[]}>= {
  "Sécurité":{description:"Une solution pensée pour renforcer la surveillance et la protection de votre maison, boutique ou bureau. Son installation et sa connectivité doivent être confirmées selon la configuration du lieu.",uses:["Surveillance d’un espace privé ou professionnel","Alerte et contrôle selon les fonctions du modèle","Complément d’un dispositif de sécurité existant"],features:["Installation adaptée au lieu","Utilisation quotidienne simple","Conseil de configuration disponible"]},
  "Projecteurs":{description:"Un projecteur compact conçu pour afficher films, présentations et contenus multimédias sur grand écran. La qualité finale dépend de la luminosité de la pièce, de la distance de projection et de la source vidéo.",uses:["Films et divertissement à la maison","Présentations en réunion ou formation","Projection mobile dans différents espaces"],features:["Format compact et transportable","Connexion à plusieurs sources selon le modèle","Réglage de l’image selon la pièce"]},
  "Drones":{description:"Un drone destiné à la découverte de la prise de vue aérienne et au pilotage de loisir. L’autonomie, la portée et les fonctions caméra doivent être confirmées avant la commande.",uses:["Prises de vue aériennes de loisir","Découverte et apprentissage du pilotage","Création de contenus en extérieur"],features:["Conception transportable","Pilotage par télécommande","Fonctions caméra selon le modèle"]},
  "Informatique":{description:"Un accessoire informatique destiné à améliorer la connectivité, l’organisation ou le confort de votre poste de travail. La compatibilité avec votre ordinateur ou téléphone est vérifiée avant achat.",uses:["Équipement du bureau","Travail mobile et déplacements","Extension ou amélioration de la connectique"],features:["Compatibilité à confirmer","Format pratique au quotidien","Support de choix avant commande"]},
  "Chargeurs":{description:"Une solution de recharge pratique pour vos appareils compatibles. La puissance, le connecteur et le protocole de charge doivent correspondre à votre téléphone ou accessoire.",uses:["Recharge à la maison ou au bureau","Utilisation quotidienne et mobilité","Complément d’un espace de travail connecté"],features:["Recharge pratique","Compatibilité vérifiée avant achat","Utilisation simple"]},
  "Audio":{description:"Un équipement audio conçu pour écouter vos contenus, communiquer ou animer un espace. L’autonomie, la connectivité et les accessoires inclus varient selon le modèle.",uses:["Musique et divertissement","Appels et communication","Utilisation mobile ou à domicile"],features:["Connexion sans fil selon le modèle","Commandes accessibles","Format adapté à un usage quotidien"]},
  "Éclairage":{description:"Un éclairage conçu pour améliorer la visibilité, l’ambiance ou la création de contenu. La puissance, la température de couleur et le mode d’alimentation sont confirmés selon le modèle.",uses:["Création photo et vidéo","Éclairage d’appoint","Ambiance et confort intérieur"],features:["Éclairage orienté selon le modèle","Installation simple","Intensité adaptée à l’usage"]},
  "Électrique":{description:"Un équipement électrique pratique pour la maison, le véhicule ou les activités quotidiennes. Son alimentation, sa puissance et les conditions d’utilisation doivent être respectées.",uses:["Usage domestique","Dépannage et mobilité","Équipement pratique du quotidien"],features:["Format fonctionnel","Utilisation guidée","Caractéristiques confirmées avant commande"]},
  "Maison & quotidien":{description:"Un produit pratique conçu pour faciliter les usages courants à la maison, au bureau ou en déplacement. Les dimensions, matériaux et accessoires sont confirmés avant validation.",uses:["Confort à la maison","Usage au bureau","Déplacements et activités quotidiennes"],features:["Conception pratique","Entretien simple","Format adapté à un usage régulier"]},
  "PERCHE A SELFIE":{description:"Un support conçu pour stabiliser le téléphone et faciliter les photos, vidéos, appels ou directs. La compatibilité avec votre smartphone et les modes de fixation sont confirmés avant commande.",uses:["Selfies et photos de groupe","Vidéo et diffusion en direct","Création de contenu mobile"],features:["Réglage pratique","Transport facile","Fixation adaptée au smartphone"]},
};

export default function ProductDetail(){
  const {slug}=useParams<{slug:string}>();
  const product=products.find(p=>p[0]===slug);
  if(!product)return <main className="inner-page"><SiteHeader/><section className="product-not-found"><h1>Produit introuvable</h1><p>Ce produit n’est plus disponible dans le catalogue actuel.</p><a href="/boutique"><ArrowLeft size={16}/>Retour à la boutique</a></section><SiteFooter/></main>;
  const [id,name,category,price,image,status]=product;
  const content=categoryCopy[category]||categoryCopy["Maison & quotidien"];
  const fullImage=image.startsWith("http")?image:root+image;
  const add=()=>{const key="fantomas-cart";const current=JSON.parse(localStorage.getItem(key)||"[]") as Array<{id:string;title:string;category:string;price:number;quantity:number;image:string}>;const found=current.find(item=>item.id===id);const next=found?current.map(item=>item.id===id?{...item,quantity:item.quantity+1}:item):[...current,{id,title:name,category,price,quantity:1,image:fullImage}];localStorage.setItem(key,JSON.stringify(next));window.dispatchEvent(new Event("fantomas-cart-updated"));window.location.href="/panier"};
  const wa=`https://wa.me/22371000048?text=${encodeURIComponent(`Bonjour Fantomas Tech, je souhaite commander :\n• ${name}\n• Prix : ${money(price)}\n• Référence : ${id}\n\nMerci de confirmer la disponibilité, la garantie et la livraison à Bamako.`)}`;
  return <main className="product-detail-page"><SiteHeader/><section className="pdp-breadcrumb"><a href="/boutique"><ArrowLeft size={15}/>Boutique</a><span>/</span><span>{category}</span></section><section className="pdp-hero"><div className="pdp-gallery"><span>{category}</span><img src={fullImage} alt={name}/><small>Visuel du produit • La présentation peut varier selon l’arrivage</small></div><div className="pdp-summary"><div className="pdp-status"><i/>{status}</div><h1>{name}</h1><p>{content.description}</p><strong>{money(price)}</strong><div className="pdp-actions"><button onClick={add}><ShoppingBag size={18}/>Ajouter au panier</button><a href={wa} target="_blank" rel="noreferrer"><MessageCircle size={18}/>Commander sur WhatsApp</a></div><small>Le stock, la garantie et les conditions de livraison sont confirmés avant validation.</small></div></section><section className="pdp-content"><article><span>UTILISATIONS RECOMMANDÉES</span><h2>À quoi sert ce produit ?</h2><ul>{content.uses.map(item=><li key={item}><CheckCircle2 size={18}/><span>{item}</span></li>)}</ul></article><article><span>POINTS ESSENTIELS</span><h2>Ce qu’il faut retenir</h2><ul>{content.features.map(item=><li key={item}><Zap size={18}/><span>{item}</span></li>)}</ul></article></section><section className="pdp-assurance"><div><ShieldCheck size={22}/><span><b>Garantie clarifiée</b><small>Selon le produit et l’arrivage</small></span></div><div><Truck size={22}/><span><b>Livraison à Bamako</b><small>Frais et délai confirmés</small></span></div><div><MessageCircle size={22}/><span><b>Conseil local</b><small>Avant et après la commande</small></span></div></section><SiteFooter/></main>;
}
