import type {ProductRecord} from "./supabase";

const categoryCopy:Record<string,{intro:string;benefits:string[];uses:string[];specs:[string,string][]}>={
 "Sécurité":{intro:"un équipement pensé pour renforcer la surveillance et la tranquillité de vos espaces, avec une utilisation simple au quotidien.",benefits:["Surveillance plus claire de la zone équipée","Solution adaptée à la maison, à la boutique ou au bureau","Accompagnement local pour la configuration"],uses:["Sécuriser une entrée ou une pièce","Surveiller un commerce ou un bureau","Compléter une installation de sécurité existante"],specs:[["Usage","Sécurité et surveillance"],["Installation","Selon la configuration du site"],["Assistance","Conseil Fantomas Tech à Bamako"]]},
 "Projecteurs":{intro:"une solution de projection compacte pour profiter de contenus sur grand écran à la maison, au bureau ou lors de présentations.",benefits:["Image grand format dans un appareil compact","Installation flexible selon votre espace","Usage divertissement ou professionnel"],uses:["Films et séries à la maison","Présentations professionnelles","Projection mobile ou événementielle"],specs:[["Usage","Projection vidéo"],["Positionnement","À adapter au recul disponible"],["Compatibilité","À confirmer selon vos appareils"]]},
 "Drones":{intro:"un appareil aérien conçu pour découvrir la prise de vue en hauteur et réaliser des images sous un angle différent.",benefits:["Format transportable","Pilotage à distance","Prise de vue aérienne selon le modèle"],uses:["Loisir et découverte","Création de contenus","Observation en extérieur"],specs:[["Usage","Vol de loisir et prise de vue"],["Environnement","Extérieur dégagé recommandé"],["Autonomie","Variable selon le modèle et l’usage"]]},
 "Informatique":{intro:"un accessoire pratique pour améliorer la connectivité, l’organisation ou le confort de votre poste de travail.",benefits:["Installation rapide","Format adapté au bureau et à la mobilité","Meilleure organisation des équipements"],uses:["Équiper un ordinateur portable","Optimiser un poste de travail","Faciliter les déplacements professionnels"],specs:[["Usage","Informatique et bureau"],["Compatibilité","À vérifier avec votre appareil"],["Support","Conseil avant achat disponible"]]},
 "Chargeurs":{intro:"une solution de recharge pratique pour garder vos appareils disponibles à la maison, au bureau ou en déplacement.",benefits:["Recharge simple au quotidien","Format pratique et facile à transporter","Compatibilité vérifiée avant commande"],uses:["Recharge au bureau","Recharge à domicile","Équipement de mobilité"],specs:[["Usage","Recharge d’appareils compatibles"],["Alimentation","Selon le modèle"],["Compatibilité","À confirmer avant validation"]]},
 "Éclairage":{intro:"une solution lumineuse polyvalente pour améliorer l’ambiance, la visibilité ou la création de contenus.",benefits:["Éclairage ciblé et pratique","Format adapté à différents espaces","Mise en service simple"],uses:["Éclairage d’appoint","Photo et vidéo","Bureau, chambre ou commerce"],specs:[["Usage","Éclairage intérieur ou création"],["Installation","Selon le support et le modèle"],["Alimentation","À confirmer selon le produit"]]},
 "Audio":{intro:"un équipement audio conçu pour rendre l’écoute, les appels ou les moments de divertissement plus agréables.",benefits:["Utilisation intuitive","Format adapté à la mobilité","Son pratique au quotidien"],uses:["Musique et divertissement","Appels et mobilité","Maison, bureau ou événement"],specs:[["Usage","Audio et communication"],["Connexion","Selon le modèle"],["Autonomie","Variable selon le volume et l’usage"]]},
 "Électrique":{intro:"un équipement électrique pratique destiné à simplifier une tâche précise à la maison, au bureau ou en déplacement.",benefits:["Gain de temps dans l’usage prévu","Format pratique","Conseil local avant mise en service"],uses:["Usage domestique","Besoin ponctuel ou professionnel","Équipement complémentaire"],specs:[["Usage","Équipement électrique"],["Alimentation","Selon le modèle"],["Précaution","Respecter la notice et la tension indiquée"]]},
};

const fallback={intro:"un équipement sélectionné par Fantomas Tech pour répondre à un besoin concret avec une commande simple et un accompagnement local.",benefits:["Produit sélectionné pour un usage quotidien","Prix affiché clairement en XOF","Conseil et confirmation avant commande"],uses:["Maison et quotidien","Bureau ou activité professionnelle","Équipement personnel"],specs:[["Distribution","Fantomas Tech — Bamako"],["Disponibilité","À confirmer avant commande"],["Assistance","Support local disponible"]] as [string,string][]};

export function productContent(product:ProductRecord){
 const base=categoryCopy[product.category]||fallback;
 const custom=product.description?.trim();
 const explicit=custom&&custom.length>55&&!custom.includes("Commande et disponibilité à confirmer")?custom:`${product.name} est ${base.intro} Fantomas Tech vous accompagne pour vérifier la compatibilité, les accessoires nécessaires et les conditions de livraison avant la validation de votre commande.`;
 return {...base,description:explicit};
}
