"use client";

import {useMemo,useState} from "react";
import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";
import {CheckCircle2,ChevronDown,Clapperboard,HelpCircle,Home,Lightbulb,MessageCircle,Moon,Send,Smartphone,Sparkles,Tv,Wifi,Zap} from "lucide-react";

const products=[
 {id:1,name:"PROJECTEUR HY300 PRO 4K",price:60000,room:"Salon & cinéma",image:"https://www.fantomas.tech/_next/image?q=75&url=%2Fapi%2Fproduct-images%2F80&w=3840",badge:"Produit vedette",specs:["Android","Wi‑Fi","Cinéma portable"]},
 {id:2,name:"PROJECTEUR HY320 MINI 4K",price:60000,room:"Salon & cinéma",image:"https://www.fantomas.tech/_next/image?q=75&url=%2Fapi%2Fproduct-images%2F76&w=3840",badge:"Format compact",specs:["Compact","Rotatif","Compatible 4K"]},
 {id:3,name:"CAMERA DE SURVEILLANCE INDOOR",price:20000,room:"Maison & bureau",image:"https://www.fantomas.tech/_next/image?q=75&url=%2Fapi%2Fproduct-images%2F117&w=3840",badge:"Maison",specs:["Surveillance intérieure","Contrôle connecté","Format discret"]},
 {id:4,name:"WIRELESS CHARGING QI STANDARD",price:12000,room:"Maison & bureau",image:"https://www.fantomas.tech/_next/image?q=75&url=%2Fapi%2Fproduct-images%2F90&w=3840",badge:"Recharge pratique",specs:["Recharge sans fil","Design fin","Smartphones compatibles"]},
 {id:5,name:"LAMPE INTELLIGENTE",price:3000,room:"Maison & bureau",image:"https://www.fantomas.tech/_next/image?q=75&url=%2Fapi%2Fproduct-images%2F109&w=3840",badge:"Éclairage malin",specs:["Éclairage automatique","Lumière douce","Installation facile"]}
];
const rooms=["Toute la maison","Salon & cinéma","Maison & bureau"];
const money=(n:number)=>new Intl.NumberFormat("fr-FR").format(n)+" XOF";

export default function Maison(){
 const [preset,setPreset]=useState<"cinema"|"night"|"eco">("cinema");
 const [room,setRoom]=useState("Toute la maison");
 const [activeProduct,setActiveProduct]=useState(products[0]);
 const [specOpen,setSpecOpen]=useState(true);
 const visible=useMemo(()=>products.filter(p=>room==="Toute la maison"||p.room===room),[room]);
 const wa=(name:string,price?:number)=>`https://wa.me/22371000048?text=${encodeURIComponent(`Bonjour Fantomas Tech, je souhaite des informations sur :\n• ${name}${price?`\n• Prix : ${money(price)}`:""}\n\nMerci de me confirmer la disponibilité, la compatibilité et les conditions de livraison à Bamako.`)}`;
 return <main className="inner-page smart-page">
  <SiteHeader/>
  <section className="smart-hero"><div className="smart-copy"><p className="kicker"><Sparkles size={14}/> MAISON CONNECTÉE • BAMAKO</p><h1>Plus de confort. <em>Moins de friction.</em></h1><p>Créez un espace plus agréable avec projection vidéo, surveillance intérieure et accessoires connectés sélectionnés pour le quotidien.</p><div className="smart-tags"><span><Wifi size={15}/>Connectivité selon le produit</span><span><Smartphone size={15}/>Usages mobiles</span><span><Home size={15}/>Installation accompagnée</span></div><div className="hero-buttons"><a className="btn primary" href="#smart-products">Explorer les équipements</a><a className="btn outline" href={wa("un projet de maison connectée")}><MessageCircle size={15}/>Composer mon espace</a></div></div><div className="smart-hero-visual"><img src="https://www.fantomas.tech/images/home/home-connected.png" alt="Maison connectée avec équipements Fantomas Tech"/><div className="smart-orbit o1"><Tv size={18}/><span>Projection<small>Salon & cinéma</small></span></div><div className="smart-orbit o2"><Smartphone size={18}/><span>Contrôle<small>Depuis votre mobile</small></span></div><div className="smart-orbit o3"><Zap size={18}/><span>Énergie<small>Usage maîtrisé</small></span></div></div></section>

  <section className="smart-scenes section"><div className="smart-heading"><p className="kicker"><span/> SIMULATEUR D’AMBIANCE</p><h2>Un espace. Plusieurs <em>scénarios.</em></h2><p>Explorez des idées de configuration. L’équipe vérifie ensuite la compatibilité réelle des produits avant votre commande.</p></div><div className="scene-tabs" role="tablist"><button className={preset==="cinema"?"active":""} onClick={()=>setPreset("cinema")}><Clapperboard size={17}/>Soirée cinéma</button><button className={preset==="night"?"active cyan":""} onClick={()=>setPreset("night")}><Moon size={17}/>Confort de nuit</button><button className={preset==="eco"?"active orange":""} onClick={()=>setPreset("eco")}><Zap size={17}/>Énergie maîtrisée</button></div><div className={`scene-preview ${preset}`}>
   <div className="scene-room"><img src={preset==="cinema"?"https://www.fantomas.tech/_next/image?q=75&url=%2Fapi%2Fproduct-images%2F80&w=3840":preset==="night"?"https://www.fantomas.tech/_next/image?q=75&url=%2Fapi%2Fproduct-images%2F117&w=3840":"https://www.fantomas.tech/_next/image?q=75&url=%2Fapi%2Fproduct-images%2F109&w=3840"} alt={preset==="cinema"?"Projecteur HY300 Pro pour une ambiance cinéma":preset==="night"?"Caméra Indoor pour le confort de nuit":"Lampe intelligente pour une énergie maîtrisée"}/><div className="scene-image-label"><span>{preset==="cinema"?"HY300 PRO 4K":preset==="night"?"CAMÉRA INDOOR":"LAMPE INTELLIGENTE"}</span><small>Produit Fantomas Tech</small></div></div>
   <div className="scene-copy">{preset==="cinema"&&<><Tv size={31}/><small>MODE CINÉMA</small><h3>Transformez le salon en espace de projection.</h3><p>Associez un projecteur compact, une source connectée et les accessoires adaptés à la configuration de votre pièce.</p></>}{preset==="night"&&<><Moon size={31}/><small>MODE NUIT</small><h3>Gardez l’essentiel accessible et discret.</h3><p>Combinez surveillance intérieure et équipements pratiques pour contrôler votre environnement sans complexité.</p></>}{preset==="eco"&&<><Zap size={31}/><small>MODE ÉCO</small><h3>Organisez les usages énergétiques du quotidien.</h3><p>Choisissez des accessoires cohérents avec vos appareils et votre solution d’énergie, après vérification technique.</p></>}</div>
  </div></section>

  <section id="smart-products" className="smart-catalog section"><div className="smart-heading"><p className="kicker"><span/> SÉLECTION SMART LIVING</p><h2>Équipez chaque <em>usage.</em></h2></div><div className="room-filters" role="tablist">{rooms.map(r=><button key={r} className={room===r?"active":""} onClick={()=>setRoom(r)} role="tab" aria-selected={room===r}>{r}</button>)}</div><div className="smart-grid">{visible.map(p=><article key={p.id}><div className="smart-product-image"><img src={p.image} alt={p.name}/><span>{p.badge}</span></div><div className="smart-product-copy"><small>{p.room}</small><h3>{p.name}</h3><div className="smart-ecosystem">{p.specs.map(s=><span key={s}>{s}</span>)}</div><ul>{p.specs.map(s=><li key={s}><CheckCircle2 size={14}/>{s}</li>)}</ul><div><strong>{money(p.price)}</strong><span className="smart-card-actions"><button onClick={()=>{setActiveProduct(p);document.getElementById("smart-detail")?.scrollIntoView({behavior:"smooth"})}}>Détails</button><a href={wa(p.name,p.price)} target="_blank" rel="noreferrer"><Send size={15}/>Commander</a></span></div></div></article>)}</div></section>

  <section id="smart-detail" className="smart-detail section"><div className="smart-detail-gallery"><span>{activeProduct.badge}</span><img src={activeProduct.image} alt={`Vue détaillée de ${activeProduct.name}`}/><div className="gallery-dots"><i/><i/><i/></div></div><div className="smart-detail-copy"><p className="kicker"><span/> FICHE PRODUIT</p><small>{activeProduct.room}</small><h2>{activeProduct.name}</h2><strong>{money(activeProduct.price)}</strong><p>Consultez les points essentiels, puis demandez confirmation à l’équipe Fantomas Tech pour la compatibilité et les conditions applicables.</p><button className="spec-toggle" onClick={()=>setSpecOpen(!specOpen)} aria-expanded={specOpen}><span>Spécifications principales</span><ChevronDown className={specOpen?"open":""} size={18}/></button>{specOpen&&<div className="spec-matrix">{activeProduct.specs.map((s,i)=><div key={s}><small>POINT 0{i+1}</small><b>{s}</b></div>)}<div><small>DISPONIBILITÉ</small><b>À confirmer avant commande</b></div></div>}<div className="detail-actions"><a className="btn primary" href={wa(activeProduct.name,activeProduct.price)} target="_blank" rel="noreferrer"><Send size={15}/>Commander sur WhatsApp</a><a className="btn outline" href={wa(`une question sur ${activeProduct.name}`)} target="_blank" rel="noreferrer"><HelpCircle size={15}/>Poser une question</a></div></div></section>

  <div className="smart-sticky" aria-label="Achat rapide"><span><small>PRODUIT SÉLECTIONNÉ</small><b>{activeProduct.name}</b></span><strong>{money(activeProduct.price)}</strong><a href={wa(activeProduct.name,activeProduct.price)} target="_blank" rel="noreferrer"><Send size={15}/>Commander</a></div>

  <section className="smart-cta"><div><Lightbulb size={31}/><span><small>VOTRE PROJET SMART LIVING</small><h2>Composez une maison connectée qui vous ressemble.</h2><p>Décrivez votre pièce, vos appareils et votre objectif. Fantomas Tech vous aide à sélectionner une configuration cohérente et à confirmer les compatibilités.</p></span></div><a className="btn primary" href={wa("une configuration Maison connectée sur mesure")}><Send size={15}/>Demander un conseil</a></section>
  <SiteFooter/>
 </main>
}
