export type Category="Solaire & Énergie"|"Sécurité & 4G"|"Tutoriels & Astuces"|"Guides d’achat";
export type Article={id:string;title:string;excerpt:string;category:Category;readTime:string;date:string;badge:string;author:string;featured?:boolean;points:string[]};

export const articles:Article[]=[
 {id:"batterie",title:"Lithium LiFePO₄ ou Gel : quelle batterie choisir à Bamako ?",excerpt:"Comprenez les différences de capacité utile, d’entretien, de poids et de budget avant de dimensionner votre stockage.",category:"Solaire & Énergie",readTime:"6 min",date:"04 août 2026",badge:"Guide essentiel",author:"Équipe Fantomas",featured:true,points:["Définir les appareils prioritaires et leur durée d’utilisation.","Comparer le coût initial avec la fréquence d’utilisation prévue.","Faire confirmer la capacité, l’onduleur et les protections par un technicien."]},
 {id:"chantier",title:"Sécuriser un chantier isolé sans Wi‑Fi fixe",excerpt:"Découvrez les conditions nécessaires à une surveillance 4G autonome et les vérifications à réaliser avant l’installation.",category:"Sécurité & 4G",readTime:"4 min",date:"01 août 2026",badge:"Sécurité 4G",author:"Équipe Fantomas",featured:true,points:["Vérifier la couverture mobile à l’emplacement exact.","Choisir un angle de vue qui limite les zones masquées.","Prévoir l’alimentation, le stockage et les alertes adaptées."]},
 {id:"onduleur",title:"Calculer la puissance d’onduleur nécessaire pour une villa",excerpt:"Une méthode pratique pour inventorier climatiseur, réfrigérateur, éclairage et équipements sensibles sans sous-dimensionner.",category:"Tutoriels & Astuces",readTime:"5 min",date:"28 juillet 2026",badge:"Tutoriel pratique",author:"Équipe Fantomas",points:["Relever la puissance sur l’étiquette de chaque appareil.","Distinguer consommation normale et courant de démarrage.","Prévoir une marge et les futurs équipements."]},
 {id:"harmattan",title:"Entretenir ses panneaux solaires pendant l’harmattan",excerpt:"Trois réflexes prudents pour limiter l’impact de la poussière sans endommager la surface des panneaux.",category:"Tutoriels & Astuces",readTime:"3 min",date:"22 juillet 2026",badge:"Entretien",author:"Équipe Fantomas",points:["Intervenir lorsque les panneaux sont froids et accessibles en sécurité.","Utiliser de l’eau propre et un matériel non abrasif.","Faire contrôler l’installation en cas de baisse inhabituelle de production."]},
 {id:"projecteur",title:"Projecteur intelligent ou télévision : quel choix pour le salon ?",excerpt:"Comparez l’espace disponible, la luminosité, le son et la consommation avant d’aménager votre coin cinéma.",category:"Guides d’achat",readTime:"5 min",date:"15 juillet 2026",badge:"Maison connectée",author:"Équipe Fantomas",points:["Mesurer la distance de projection et la taille d’image souhaitée.","Observer la lumière ambiante aux heures d’utilisation.","Prévoir le son, les connexions et la position des câbles."]},
 {id:"camera",title:"Où installer les caméras d’une maison ou d’une boutique ?",excerpt:"Priorisez les accès et les zones de passage tout en limitant les angles morts et les contre-jours.",category:"Sécurité & 4G",readTime:"4 min",date:"10 juillet 2026",badge:"Guide sécurité",author:"Équipe Fantomas",points:["Cartographier portes, fenêtres et zones de passage.","Éviter les sources lumineuses directement face à l’objectif.","Respecter les espaces privés et informer les personnes concernées."]},
];

export const categories=["Tous","Solaire & Énergie","Sécurité & 4G","Tutoriels & Astuces","Guides d’achat"] as const;
